/*******************************************************************************
 * Copyright (c) 2000, 2013 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
		TokenNameWHITESPACE = 1000,
		TokenNameCOMMENT_LINE = 1001,
		TokenNameCOMMENT_BLOCK = 1002,
		TokenNameCOMMENT_JAVADOC = 1003;

	int      TokenNameIdentifier = 22,
      TokenNameabstract = 51,
      TokenNameassert = 73,
      TokenNameboolean = 98,
      TokenNamebreak = 74,
      TokenNamebyte = 99,
      TokenNamecase = 100,
      TokenNamecatch = 101,
      TokenNamechar = 102,
      TokenNameclass = 67,
      TokenNamestruct = 69,
      TokenNamecontinue = 75,
      TokenNameconst = 117,
      TokenNamedefault = 76,
      TokenNamedo = 77,
      TokenNamedouble = 103,
      TokenNameelse = 112,
      TokenNameenum = 70,
      TokenNameextends = 97,
      TokenNamefalse = 38,
      TokenNamefinal = 52,
      TokenNamefinally = 110,
      TokenNamefloat = 104,
      TokenNamefor = 78,
      TokenNamegoto = 118,
      TokenNameif = 79,
      TokenNameimplements = 115,
      TokenNameimport = 105,
      TokenNameinstanceof = 17,
      TokenNameint = 106,
      TokenNameinterface = 68,
      TokenNamelong = 107,
      TokenNamenative = 53,
      TokenNamenew = 36,
      TokenNamenull = 39,
      TokenNamepackage = 96,
      TokenNameprivate = 54,
      TokenNameprotected = 55,
      TokenNamepublic = 56,
      TokenNamereturn = 80,
      TokenNameshort = 108,
      TokenNamestatic = 40,
      TokenNamestrictfp = 57,
      TokenNamesuper = 34,
      TokenNameswitch = 81,
      TokenNamesynchronized = 41,
      TokenNamethis = 35,
      TokenNamethrow = 82,
      TokenNamethrows = 113,
      TokenNametransient = 58,
      TokenNametrue = 42,
      TokenNametry = 83,
      TokenNamevoid = 109,
      TokenNamevolatile = 59,
      TokenNamewhile = 72,
      TokenNameIntegerLiteral = 43,
      TokenNameLongLiteral = 44,
      TokenNameFloatingPointLiteral = 45,
      TokenNameDoubleLiteral = 46,
      TokenNameCharacterLiteral = 47,
      TokenNameStringLiteral = 48,
      TokenNamePLUS_PLUS = 1,
      TokenNameMINUS_MINUS = 2,
      TokenNameEQUAL_EQUAL = 19,
      TokenNameLESS_EQUAL = 12,
      TokenNameGREATER_EQUAL = 13,
      TokenNameNOT_EQUAL = 20,
      TokenNameLEFT_SHIFT = 18,
      TokenNameRIGHT_SHIFT = 14,
      TokenNameUNSIGNED_RIGHT_SHIFT = 16,
      TokenNamePLUS_EQUAL = 85,
      TokenNameMINUS_EQUAL = 86,
      TokenNameMULTIPLY_EQUAL = 87,
      TokenNameDIVIDE_EQUAL = 88,
      TokenNameAND_EQUAL = 89,
      TokenNameOR_EQUAL = 90,
      TokenNameXOR_EQUAL = 91,
      TokenNameREMAINDER_EQUAL = 92,
      TokenNameLEFT_SHIFT_EQUAL = 93,
      TokenNameRIGHT_SHIFT_EQUAL = 94,
      TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 95,
      TokenNameOR_OR = 31,
      TokenNameAND_AND = 30,
      TokenNamePLUS = 4,
      TokenNameMINUS = 5,
      TokenNameNOT = 62,
      TokenNameREMAINDER = 8,
      TokenNameXOR = 23,
      TokenNameAND = 21,
      TokenNameMULTIPLY = 6,
      TokenNameOR = 26,
      TokenNameTWIDDLE = 63,
      TokenNameDIVIDE = 9,
      TokenNameGREATER = 15,
      TokenNameLESS = 11,
      TokenNameLPAREN = 24,
      TokenNameRPAREN = 25,
      TokenNameLBRACE = 49,
      TokenNameRBRACE = 32,
      TokenNameLBRACKET = 10,
      TokenNameRBRACKET = 64,
      TokenNameSEMICOLON = 28,
      TokenNameQUESTION = 29,
      TokenNameCOLON = 61,
      TokenNameCOMMA = 33,
      TokenNameDOT = 3,
      TokenNameEQUAL = 71,
      TokenNameAT = 37,
      TokenNameELLIPSIS = 114,
      TokenNameARROW = 111,
      TokenNameCOLON_COLON = 7,
      TokenNameBeginLambda = 50,
      TokenNameBeginIntersectionCast = 65,
      TokenNameBeginTypeArguments = 84,
      TokenNameElidedSemicolonAndRightBrace = 66,
      TokenNameAT308 = 27,
      TokenNameAT308DOTDOTDOT = 116,
      TokenNameEOF = 60,
      TokenNameERROR = 119;
}
